<?php
    $this->headScript()->appendFile('/js/ckeditor/ckeditor.js');
    $this->headScript()->appendFile('/js/access-maagement-helper.js');
?>
<div class="row ">
    <h1><i class="fa fa-lock"></i> <?php echo $this->translate('EDIT_ACCESS_MANAGEMENT'); ?></h1>
</div>
<div class="row ">

    <div class="col-md-6">
        <h2><i class="fa fa-list-ul"></i> <?php echo $this->translate('ACCESS_OPTIONS'); ?></h2>
        <?php echo $this->form($this->form); ?>
    </div>
    <div class="col-md-6">
        <h2><i class="fa fa-eye"></i> <?php echo $this->translate('ACCESS_PREVIEW'); ?></h2>
        <div id="access-preview-wrapper"></div>
    </div>

</div>