<div class="row">
    <h1>
        <i class="fa fa-newspaper-o"></i>
        <?php echo $this->escapeHtml($this->template->getName()); ?>
    </h1>
</div>

<div class="row">
    <div class="col-md-6">
        <h3><i class="fa fa-list-alt"></i> <?php echo $this->translate('TEMPLATE_DETAILS'); ?></h3>

        <dl class="dl-horizontal">
            <dt><?php echo $this->translate('NAME'); ?></dt>
                <dd><?php echo $this->escapeHtml($this->template->getName()); ?></dd>
            <dt><?php echo $this->translate('EVENT'); ?></dt>
                <dd><?php echo $this->escapeHtml($this->template->getEvent()); ?></dd>
            <dt><?php echo $this->translate('SUBJECT'); ?></dt>
                <dd><?php echo $this->escapeHtml($this->template->getSubject()); ?></dd>
        </dl>

        <dl class="dl-horizontal">
            <dt><?php echo $this->translate('CREATED'); ?></dt>
                <dd><?php echo $this->dateFormat($this->template->getCreatedAt(), IntlDateFormatter::MEDIUM); ?></dd>
            <?php if (!is_null($this->template->getUpdatedAt())) : ?>
                <dt><?php echo $this->translate('LAST_UPDATED'); ?></dt>
                    <dd><?php echo $this->dateFormat($this->template->getUpdatedAt(), IntlDateFormatter::MEDIUM); ?></dd>
            <?php endif; ?>
        </dl>

        <dl class="dl-horizontal">
            <dt><?php echo $this->translate('BODY_HTML'); ?></dt>
                <dd>
                    <div class="well template-text-wrapper ">
                        <?php echo $this->escapeHtml($this->template->getBody()); ?>
                    </div>
                </dd>
            <dt><?php echo $this->translate('BODY_FORMATTED'); ?></dt>
                <dd>
                    <div class="well template-text-wrapper ">
                        <?php echo $this->template->getBody(); ?>
                    </div>
                </dd>
        </dl>

    </div>
    <div class="col-md-6">

        <h3><i class="fa fa-circle-o"></i> <?php echo $this->translate('AVAILABLE_PARAMETERS'); ?></h3>
        <?php echo $this->RenderTemplateParameters($this->template); ?>
    </div>
</div>