<div class="brandinguoe header">
	<div id="wrapper">
		<div id="header">
			<h1>
				<a title="Go back to the University of Exeter home page" href="http://www.exeter.ac.uk"><img width="162" height="60" class="logo" alt="Go back to the University of Exeter home page" src="https://www.exeter.ac.uk/media/universityofexeter/webteam/styleassets/images/logo.gif"></a>
			</h1>
			<div id="supernav">
				<p><a href="http://www.exeter.ac.uk">Home</a> | <a href="http://www.exeter.ac.uk/contact/">Contact us</a> | <a href="http://www.exeter.ac.uk/staff/">Staff</a> | <a href="http://www.exeter.ac.uk/students/">Students</a> | <a href="https://my.exeter.ac.uk/">MyExeter</a> | <a href="http://www.exeter.ac.uk/sitemap/">Site map</a> |</p>
			</div>
		</div>
	</div>
</div>