<div class="brandinguoe footer">
    <div id="wrapper">
        <div id="footer">
            <div id="footerleft"><p><a href="http://www.exeter.ac.uk/usingoursite/">Using our site</a>&nbsp;|&nbsp;<a href="http://www.exeter.ac.uk/freedom/">Freedom of Information</a>&nbsp;|&nbsp;<a href="http://www.exeter.ac.uk/dataprotection/">Data Protection</a>&nbsp;|&nbsp;<a href="http://www.exeter.ac.uk/copyright/">Copyright &amp; disclaimer</a>&nbsp;|&nbsp;<a href="http://www.exeter.ac.uk/privacy/">Privacy &amp; Cookies</a>&nbsp;|&nbsp;</p></div>
        </div>
    </div>
</div>