<div class="brandinguoe footer">
    <div id="wrapper">
        <div id="footer">
            <div id="footerleft"><p><a href="http://www.exeter.ac.uk/usingoursite/">Using our site</a>&nbsp;|&nbsp;<a href="http://www.exeter.ac.uk/freedom/">Freedom of Information</a>&nbsp;|&nbsp;<a href="http://www.exeter.ac.uk/dataprotection/">Data Protection</a>&nbsp;|&nbsp;<a href="http://www.exeter.ac.uk/copyright/">Copyright &amp; disclaimer</a>&nbsp;|&nbsp;<a href="http://www.exeter.ac.uk/privacy/">Privacy &amp; Cookies</a>&nbsp;|&nbsp;</p></div>
            <div id="footerright">
                <p>
                <a href="http://www.facebook.com/exeteruni"><img width="16" height="16" alt="Facebook" src="https://www.exeter.ac.uk/media/universityofexeter/webteam/styleassets/images/facebookicon.gif"></a>
                <a href="http://twitter.com/uniofexeter"><img width="16" height="16" alt="Twitter" src="https://www.exeter.ac.uk/media/universityofexeter/webteam/styleassets/images/twittericon.png"></a>
                <a href="http://www.youtube.com/universityofexeter"><img width="16" height="16" src="https://www.exeter.ac.uk/media/universityofexeter/webteam/styleassets/images/youtubeicon.gif" alt="YouTube"></a>
                <a href="http://www.linkedin.com/groups/University-Exeter-109267?MostPopular=&amp;gid=109267"><img width="16" height="16" alt="LinkedIn" src="https://www.exeter.ac.uk/media/universityofexeter/webteam/styleassets/images/linkedinicon.gif"></a>
                <!-- AddThis Button BEGIN -->
                <a href="https://www.addthis.com/bookmark.php?v=250&amp;username=uniofexeter" class="addthis_button"><img width="125" height="16" style="border:0" alt="Bookmark and Share" src="https://s7.addthis.com/static/btn/v2/lg-share-en.gif"></a>
                <script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
                <script src="https://s7.addthis.com/js/250/addthis_widget.js#username=uniofexeter" type="text/javascript" defer="defer"></script>
                <!-- AddThis Button END -->
                </p>
            </div>
        </div>
    </div>
</div>