<div class="brandinguoe header">
	<div id="wrapper">
		<div id="header">
			<a id="skip" href="#maincontent">Skip to main content</a>
			<a title="Go back to the University of Exeter home page" href="http://www.exeter.ac.uk"><img width="162" height="60" class="logo" alt="Go back to the University of Exeter home page" src="https://www.exeter.ac.uk/media/universityofexeter/webteam/styleassets/images/logo.gif"></a>
			
			<div id="supernav">
				<p><a href="http://www.exeter.ac.uk">Home</a> | <a href="http://www.exeter.ac.uk/contact/">Contact us</a> | <a href="http://www.exeter.ac.uk/staff/">Staff</a> | <a href="http://www.exeter.ac.uk/students/">Students</a> | <a href="https://my.exeter.ac.uk/">MyExeter</a> | <a href="http://www.exeter.ac.uk/sitemap/">Site map</a> |</p>
			</div>
			
			<div id="search">
				<form id="searchbox" name="htsearchform" method="get" action="http://search.exeter.ac.uk/search/search.cgi">
					<input type="text" title="Search the site" maxlength="80" accesskey="q" value="" class="query" name="query">
					<input type="submit" value="Search" class="button">
					<input type="hidden" name="collection" value="all-exeter-uni">
					<input type="hidden" value="simple" name="form">
				</form>
			</div>
		 	
		</div>
	</div>
</div>