<div class="row ">
	<h1>
		<i class="fa fa-lock"></i>
		<?php echo $this->translate(is_null($this->user->getPassword()) || strlen(trim($this->user->getPassword())) == 0  ? 'ADD_PASSWORD' : 'CHANGE_PASSWORD'); ?>
	</h1>
	
	<div class="alert alert-info">
		<i class="fa fa-info-circle"></i>
		<?php echo $this->translate('PASSWORD_CONSTRAINT_RULES'); ?>
		<ul>
			<li><?php echo sprintf($this->translate('PASSWORD_MIN_LENGTH_X'), User::MIN_PASSWORD_LENGTH); ?></li>
			<li><?php echo $this->translate('PASSWORD_FAILED_UPPER_CASE'); ?></li>
			<li><?php echo $this->translate('PASSWORD_FAILED_NUMERIC'); ?></li>
			<li><?php echo $this->translate('PASSWORD_FAILED_SPECIAL_CHARACTER'); ?></li>
		</ul>
	</div>
	
	<?php echo $this->form($this->form); ?>
</div>
